### ISSUE TITLE
Orphaned conversations causing confusion

### ISSUE THREAD

**Issue by cedict** [troywilliams/moodle-mod_dialogue#35]
Hi,

We are currently using version 2.7 (2014071701) with Moodle 2.7 Stable (Build: 20150409) and using Postgres. An academic has reported an issue where the dialogue tool is reporting unread messages, but these messages cannot be seen in the UI. 

This staff member has been granted 'mod/dialogue:viewany' permission which is counting any conversations, regardless of the staff members involvement: https://github.com/troywilliams/moodle-mod_dialogue/blob/MOODLE_27_STABLE/locallib.php#L1594. For some reason, these unread messages do not have any related participants within the {dialogue_participants} table. 

Performing the following query returns 7 results (3 distinct conversationids) from 1 dialogueid:

```PLpgSQL
SELECT m.dialogueid, m.conversationid, p.conversationid
 FROM {dialogue_messages} m
 LEFT JOIN {dialogue_participants} p ON m.conversationid = p.conversationid
 WHERE p.conversationid IS NULL AND
  state IN ('open', 'closed')
```

Looking at the code, there doesn't seem to be any immediate reason why this issue has occurred, but thought I'd post this here encase anyone else has experienced a similar problem. We were able to modify the URLs to view the post, but it was not accessible through the UI, which caused confusion for the academic who was being told that there were unread messages.

Thanks

**Comment by troywilliams** [comment]
Thanks for reporting. Will try to replicate over next few days. Do you know if academic was using any bulk opener rules in that dialogue? When a bulk opener rule is used their will be no participants... but state should be marked as bulkautomated, doesn't explain how got a open or closed state. Need to try and replicate.

**Comment by cedict** [comment]
Hi Troy,

These conversations were definitely not opened using bulk opener rules - they were created singularly. I can't seem to find anything in common with conversations (apart from the academic having the 'mod/dialogue:viewany' permission.

**Comment by troywilliams** [comment]
Ok, thanks. This was a problem in a previous version of the dialogue module.
