### ISSUE TITLE
Fatal error in cron on call to file_prepare_draft_area()

### ISSUE THREAD

**Issue by colin-umn** [troywilliams/moodle-mod_dialogue#36]
We occasionally see the following error message in the cron:

> PHP Fatal error:  Call to undefined function file_prepare_draft_area() in /home/oit-moodle/2.8/docs/mod/dialogue/locallib.php on line 660

The problem appears to be that lib/filelib.php is not getting included unless something that runs prior to the dialogue task includes it.

**Comment by troywilliams** [comment]
Hi,

Thanks for reporting, Sorry I am away for two weeks so cannot fix right now. I will sort once back.

Regards

Troy

**Comment by colin-umn** [comment]
Hi Troy.  I just sent in a pull request to get this fixed.  We sometimes get these fatal errors every minute for hours until, finally, something happens to require filelib.php before this task runs.

Thanks.
Colin

**Comment by troywilliams** [comment]
Closing, thanks for the fix.

**Comment by colin-umn** [comment]
Hi Troy - Can you please also fix this in the 3.0 branch?  The fix is not in there.
