### ISSUE TITLE
Bulk open rules send notification emails to inactive / suspended users

### ISSUE THREAD

**Issue by cedict** [troywilliams/moodle-mod_dialogue#38]
Hi,

We've had reports of notification emails sending to suspended students from academic who've used the Bulk open rules on a course where all student enrolments are currently not yet active (controlled by the database enrolment method which integrates into our SIS). As the enrolments for these students are not yet active, the student cannot see the course, but an email has been sent by the dialogue tool to advise of a waiting message.

This may be as easy as changing the [get_enrolled_users](https://github.com/wcel/moodle-mod_dialogue/blob/master/lib.php#L170) call to only include active users?

**Comment by gibbisons** [comment]
Thanks for your report and apologies for the delay.  We have had a change of developer so will get to this in time. Thank you for your patience.

**Comment by gibbisons** [comment]
Can you please clarify your integration? When you say the enrolment is not active - is that in your SIS? How does that reflect in the Moodle course? Does the user have a role in the course?

**Comment by troywilliams** [comment]
Thanks for reporting, is now fixed.
