### ISSUE TITLE
Bulk opener rules are not being sent

### ISSUE THREAD

**Issue by juancs** [troywilliams/moodle-mod_dialogue#45]
This happens on Moodle 3.x. To reproduce:
- create a bulk opener rule
- Add a message in HTML format
- Execute the dialogue task.

What I get in the php log is:

[09-Sep-2016 10:19:45 Europe/Madrid] PHP Fatal error:  Call to undefined function file_prepare_draft_area() in /var/www/moodle/mod/dialogue/classes/conversation.php on line 86

**Comment by cdsmith-umn** [comment]
We are experiencing this problem at U of MN, as well.

**Comment by cdsmith-umn** [comment]
This pull request from Colin for your Moodle 2.8 version of this plugin will fix this problem:
https://github.com/wcel/moodle-mod_dialogue/pull/37

**Comment by troywilliams** [comment]
Thanks for fix, implemented. 👍
