### ISSUE TITLE
Moodle 3.5 support?

### ISSUE THREAD

**Issue by Jarvil** [troywilliams/moodle-mod_dialogue#65]
Hello,

When you will support Moodle 3.5? @troywilliams

**Comment by troywilliams** [comment]
I haven't been able to get to it, I will try to allocate some time next week. I had issues with 3.5 boost breaking some of the form elements.

 R T

**Comment by Jarvil** [comment]
Great, thanks.

**Comment by Jarvil** [comment]
Hello,

How about 3.5 support?

**Comment by Urpokarhu1** [comment]
Hello,

How about 3.5 support?

**Comment by troywilliams** [comment]
Hi Javil,

I will be targeting v3.9.x for the next release.

Kind regards,
Troy
