### ISSUE TITLE
Compatibility with Moodle 3.7

### ISSUE THREAD

**Issue by athyg** [troywilliams/moodle-mod_dialogue#73]
Hi Troy,
We are in the process of upgrading a client's Moodle to v3.7 & they're currently using the mod_dialogue plugin and would like to be able to continue using it in their upgraded site, as the Moodle messaging doesn't meet their requirements.
Are you able to upgrade the plugin for compatibility with Moodle 3.7?
Thanks,
Athy.

**Comment by Markibacsi** [comment]
Big thumbs up to all involved in the development of this plugin :)
We are upgrading from 3.3 to 3.8 and also rely on 'heavily' on Dialogue.
Any news on a possible update would be great to communicate to the staff :)

**Comment by troywilliams** [comment]
Hi,

I will be targeting v3.9.x for the next release. You can follow progress via board https://github.com/troywilliams/moodle-mod_dialogue/projects/1

Kind regards,
Troy
