### ISSUE TITLE
Moodle 3.9 support?

### ISSUE THREAD

**Issue by Urpokarhu1** [troywilliams/moodle-mod_dialogue#74]
Hello,

I would like to see 3.9 version support for this plugin.

**Comment by Urpokarhu1** [comment]
@troywilliams

**Comment by RaimundE** [comment]
Hi Troy,

like many others we'd be very thankful for an updated version of your plugin. Would it help to find some funding for your working on the project again? I'd be happy to try and mobilize a bit of money for this - pls let me know if this might be a way forward.

Thanks
Raimund

**Comment by troywilliams** [comment]
Hi Raimund,

I am in the process of putting a project plan together to update the plugin for v3.9.x. I have neglected to maintain it and It needs a lot of work. However, you will be track progress via a project board I have setup. https://github.com/troywilliams/moodle-mod_dialogue/projects/1 The board is in its infancy but it will ramp up over the coming weeks. 

Kind regards,
Troy
