### ISSUE TITLE
privacy provider php unit test failure

### ISSUE THREAD

**Issue by mnods** [troywilliams/moodle-mod_dialogue#76]
hello, thanks for your plugin, just reporting a php unit fail in case you aren't aware.

MDL 3.9.x 

Cheers
10:11:16.398 1) provider_testcase::test_all_providers_compliant with data set "mod_dialogue" ('mod_dialogue', 'mod_dialogue\privacy\provider')
10:11:16.407 .Failed asserting that false is true.
10:11:16.407 
10:11:16.407 /opt/data/go-agent/pipelines/Moodle/moodle/privacy/tests/provider_test.php:178
10:11:16.408 /opt/data/go-agent/pipelines/Moodle/moodle/lib/phpunit/classes/advanced_testcase.php:80

**Comment by troywilliams** [comment]
Hi,

I will target PrivacyAPI support in a v3.9.x release. You can follow progress via the project board
https://github.com/troywilliams/moodle-mod_dialogue/projects/1

Regards,
Troy
